### ISSUE TITLE
Auto-scrolling chat box to bottom

### ISSUE THREAD

**Issue by ideocl4st** [aeosynth/draft#103]
(With Firefox and Chrome) When chat goes on longer than the chatbox's height, the chat stays on top (or whatever) instead of scrolling to the bottom of the chat.
![screen shot 2015-01-21 at 11 31 54 pm](https://cloud.githubusercontent.com/assets/2484055/5837883/83aec79e-a1c6-11e4-9dc8-cd8f858e7743.PNG)

Also, with Safari, the chat input sticks right below the end of chat, and you cannot scroll at all with Safari, forcing you to refresh if the chat goes over the screen height.
![screen shot 2015-01-21 at 11 36 26 pm](https://cloud.githubusercontent.com/assets/2484055/5837869/5760da9c-a1c6-11e4-98fd-c32ddc81b823.PNG)

I've been trying to make it work for some time but I think this goes over my programming capability (or lack thereof)

**Comment by aeosynth** [comment]
do you *want* to be a developer? i can guide you - search [mdn](https://developer.mozilla.org/en-US/) for scrolling

**Comment by ideocl4st** [comment]
As a job or career? nope. But I do want to contribute on things.

**Comment by aeosynth** [comment]
fixed. safari is not supported.
