### ISSUE TITLE
land sorting messed up

### ISSUE THREAD

**Issue by tooomm** [aeosynth/draft#108]
I did a draft today on drafts.in and added some lands (4x forest, 4x swamp, 4x island) while waiting for the next packs. I then realized that the basics use different art and are mixed up between basics and special:
![basics messed up](https://cloud.githubusercontent.com/assets/9874850/6319032/7ab5cdc6-baae-11e4-8e8e-73e66f6fed81.png)

I'm not excatly sure how drafts.in works and how the new Fate-Booster do with the extra gainlands and sometimes fetchlands.
But this is just wrong... :)

**Comment by aeosynth** [comment]
pr welcome

**Comment by tooomm** [comment]
I can't help with that, I'm sorry. All I can do is to point out!

**Comment by sirugh** [comment]
https://github.com/aeosynth/draft/commit/4006d3e5#diff-d3bb143777a80346d955f51c1f92568dR49

**Comment by aeosynth** [comment]
these lands are special because they are guaranteed to show up in the last slot of a booster

**Comment by sirugh** [comment]
So in KTK these would still be considered 'common'?

**Comment by aeosynth** [comment]
yes. they are now common in frf as well, and only 'special' for the purposes of booster creation. the 'special' rarity is not shown to the client.

**Comment by sirugh** [comment]
Hmm. This still leaves the basic lands from the set in cards.json:
```
  "mountain": {
    "color": "colorless",
    "name": "Mountain",
    "type": "Land",
    "cmc": 0,
    "sets": {
      "FRF": {
        "rarity": "basic",
        "url": "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=391885&type=card"
      }
    }
  },

**Comment by aeosynth** [comment]
yes it does. we add basic lands to frf packs. the alternative is to not do so, in which case packs are not guaranteed to have the same amount of starting cards. we could add unhinged lands, but i like this better.

**Comment by sirugh** [comment]
Yea, I just got it. Thanks!
