### ISSUE TITLE
The card "Defeat" in Dragons of Tarkir is misidentified as 1CMC

### ISSUE THREAD

**Issue by salmonofdoubt12** [aeosynth/draft#111]
I'm not sure if the issue is on drafts.in or wherever the card data is being pulled from, but when you sort by CMC Defeat always shows up as costing 1 mana.

**Comment by ZeldaZach** [comment]
Just checked MTGJSON's `DTK.json` and it says this:
```
{"layout":"normal","type":"Sorcery","types":["Sorcery"],"colors":["Black"],"multiverseid":394534,"name":"Defeat","cmc":2,"rarity":"Common","artist":"Dave Kendall","manaCost":"{1}{B}","text":"Destroy target creature with power 2 or less.","flavor":"\"Wars are decided one life at a time.\"\n—Gvar Barzeel, Kolaghan warrior","number":"97","imageName":"defeat"},{"layout":"normal","type":"Creature — Human Warrior","types":["Creature"],"colors":["Green"],"multiverseid":394535,"name":"Den Protector","subtypes":["Human","Warrior"],"cmc":2,"rarity":"Rare","artist":"Viktor Titov","power":"2","toughness":"1","manaCost":"{1}{G}","text":"Creatures with power less than Den Protector's power can't block it.\nMegamorph {1}{G} (You may cast this card face down as a 2/2 creature for {3}. Turn it face up any time for its megamorph cost and put a +1/+1 counter on it.)\nWhen Den Protector is turned face up, return target card from your graveyard to your hand.","number":"181","watermark":"Atarka","imageName":"den protector"}
```
and in client shows it right as:
![screenshot 2015-03-22 18 42 26](https://cloud.githubusercontent.com/assets/7460172/6771874/38859cb2-d0c3-11e4-9615-dac20d73ea7b.png)

____

I'm thinking you used a card downloader from a site like MTGSalvation and there might be inaccuracies with it. **Please try re-running the Oracle tool.** CMC is not a trait that the COD file type supports.

**Comment by salmonofdoubt12** [comment]
So Drafts.in pulls card data from Oracle locally, on my computer? When I
reran Oracle nothing changed, and Defeat is categorized properly in
Cockatrice which pulls data from Oracle. I did not use a card downloader
from MTGS as far as I know.

Here is a screenshot of the problem. Would you mind going into Drafts.in
and seeing if Defeat actually shows up at 2CMC?

**Comment by aeosynth** [comment]
fixed

@ZeldaZach deleting comments can make a thread confusing; consider editing instead

**Comment by ZeldaZach** [comment]
@aeosynth I thought this was on the cockatrice github and I was responding as if he imported a deck from drafts.in and cockatrice had an issue.

Sorry for the confusion!

**Comment by aeosynth** [comment]
i know. my point remains.
