### ISSUE TITLE
Modern Masters 2015 missing cards? 

### ISSUE THREAD

**Issue by samgc3** [aeosynth/draft#117]
Several players have stated some cards appear to be missing. Most notably Nameless Inversion, Goretusk Minotaur, Culling Dias. Daybreak Coronet was mentioned but I think I've seen it, maybe not. 

Could we double check the list? Some cards may have been missing from mtgsalvation?

**Comment by samgc3** [comment]
Oops, Gorehorn Minotaur.

**Comment by dracohey** [comment]
also the Kami of Ancient Law is set as an uncommon instead of a common

**Comment by aeosynth** [comment]
updated
