### ISSUE TITLE
Modern Masters 2015 packs missing a card, not accounting for foils?

### ISSUE THREAD

**Issue by samgc3** [aeosynth/draft#118]
Packs should be 15 cards including one foil card. Not sure if the logic for that will be added so a given card could appear twice?

**Comment by aeosynth** [comment]
fixed in master

**Comment by samgc3** [comment]
Thanks! Does this do an actual foil distribution where you could have two
of one card or just an extra common?

**Comment by aeosynth** [comment]
the former

**Comment by samgc3** [comment]
Great, thanks! Did you see the other issue about missing cards? Apologies
if you already got to it.
