### ISSUE TITLE
Modern Masters 2015 AEthersnipe has incorrect spelling

### ISSUE THREAD

**Issue by samgc3** [aeosynth/draft#119]
The card won't show up properly in Cockatrice since the name doesn't match exactly.

**Comment by sirugh** [comment]
Does AEther Vial also exhibit the same problem? There is code to normalize the name in both applications: 

https://github.com/aeosynth/draft/blob/master/src/util.js#L48
https://github.com/Cockatrice/Cockatrice/blob/4a36be84a82dc9afd525d8c464181a43ba5e4d71/cockatrice/src/carddatabase.cpp#L644
