### ISSUE TITLE
Lightning Bolt does not appear to be in MM2015

### ISSUE THREAD

**Issue by salmonofdoubt12** [aeosynth/draft#122]
I could be wrong, but a few others mentioned that they've never seen a Lightning Bolt in any draft or sealed pools. I also haven't seen one.

**Comment by samgc3** [comment]
Just came to report this. I've done numerous drafts without seeing it.

**Comment by samgc3** [comment]
Can we do a full true up? We're reporting them as we find but it would be really hard to discover a rare or mythic.

**Comment by lsanwick** [comment]
Found the issue, made a PR to fix it. #123

**Comment by lsanwick** [comment]
@samgc3, Honestly, the set is in Gatherer now, but mtgjson.com hasn't updated yet, and that's where the non-spoiler cards come from. As soon as mtgjson updates, this will all go away, I think.

**Comment by ZeldaZach** [comment]
@lsanwick I spoke with Robert and he's moving currently. MTGJSON will be updated in a few days

**Comment by lsanwick** [comment]
@ZeldaZach, cool, good to know!

**Comment by tritoch** [comment]
Switched to mtgjson from spoiler.
