### ISSUE TITLE
some kind of notification for chat

### ISSUE THREAD

**Issue by tooomm** [aeosynth/draft#131]
I sometimes miss the chat because I forget to check at all, or just don't check on a regular basis during a draft or a complex sealed pool building session.
You need as much space as possible for a nice building experience, so I end up hiding the chat... but also missing many (some important) messages!

I would like to see the `Chat` text flashing for example or some other visual notification of new messages. Especially when the chat window is hidden.

**Comment by aeosynth** [comment]
yeah ok

**Comment by aeosynth** [comment]
@tritoch do you wanna try this? shouldn't be too hard.

**Comment by tooomm** [comment]
closed in favor of https://github.com/dr4fters/dr4ft/issues/53
