### ISSUE TITLE
How does custom.js pull in BFZ cards?

### ISSUE THREAD

**Issue by ideocl4st** [aeosynth/draft#132]
The simple 'make && node run.js' doesn't seem be pulling in the BFZ cards.

**Comment by aeosynth** [comment]
you must use the spoiler repo to build BFZ.json, then place that into `data/custom.json`. yes this is undocumented.

**Comment by ideocl4st** [comment]
Wow, I totally forgot about spoiler repo. Feel free to call me a lazy bum :-/

Got it all sorted now. Thank you so much.

**Comment by aeosynth** [comment]
np, this is the first time the draft repo is using it
