### ISSUE TITLE
Mouseover

### ISSUE THREAD

**Issue by tritoch** [aeosynth/draft#136]
Add mouseover text to cards showing at least the card name.

Gatherer and images were down or partially down, and the site is non-functional.

This will also increase accessibility.

**Comment by sirugh** [comment]
+1 for a11y.

**Comment by aeosynth** [comment]
sounds good. @tritoch you have commit access, go for it, add an `alt`  attribute to the cards.

**Comment by tritoch** [comment]
Alt added
