### ISSUE TITLE
Publish your deck to the other players after draft and games are over

### ISSUE THREAD

**Issue by berserkingyadis** [aeosynth/draft#137]
Good Evening.

After drafting on drafts.in for quite a while I often asked myself after the drafting and games were over: What cards were in my opponents decks?

My suggestion would be that after you have played your matches, you have the option to publish your deck list on drafts in, so that the other players can download the deck too. 

This feature would be completely optional, if a player does not want to share the cards in his deck after the draft it is his decision. But if a player wants to share his deck he can do so.

One way to implement this would be placing a "Publish Deck" Button somewhere on the right hand side on the drafting Page, maybe like this
![publish_deck](https://cloud.githubusercontent.com/assets/9959527/11157190/748630b8-8a50-11e5-8c01-52795d73b804.png)

For players that have chosen to publish their decks there would be a "Download Deck" Button in the playerlist on the left hand side of the drafting page, maybe like this
![download_deck](https://cloud.githubusercontent.com/assets/9959527/11157214/9936f870-8a50-11e5-8bc5-c035e02153fa.png)

Before I get to any coding for this, I would like to have some feedback what other people think about it.

**Comment by aeosynth** [comment]
yeah this is valid. i always thought it would be an option at game start, alongside bots/timer, and the pools would show up immediately after the draft ends, like how tappedout does it. your download deck ui seems better.

- public decks option at game start

- if enabled, show this option underneath the set codes / cube info

- download deck button, enabled when players download/copy

**Comment by berserkingyadis** [comment]
Do you mean that the decks would be made public directly after drafting and before the playing has begin?

**Comment by aeosynth** [comment]
yeah. the room might expire by the time all games are over.

**Comment by berserkingyadis** [comment]
My initial intention was to publish the decks after all the games have been played by the user. If the room expires quickly then the other users who are interested in the decks should be quick about it maybe :P.

But the way you see it seems to be another way to go. But i have never been to a draft where you know the cards in your opponents deck

**Comment by aeosynth** [comment]
this is a casual feature; i see it for drafts where people aren't expecting to play, or if they're fine with having this information public. if you want to be selective about revealing your list, you can always send it manually.

implementation: how about instead of 'download', we have  'view', that loads the list into the page, letting you modify it. that way don't have multiple download buttons.

**Comment by berserkingyadis** [comment]
since i have a bit of time now ill try doing this, but could take a while.

is there some sort of documentation?

**Comment by aeosynth** [comment]
just the code

**Comment by aeosynth** [comment]
what kind of docs would you want? you can open issue for that and maybe i'll write it

**Comment by berserkingyadis** [comment]
Just kind of small guide/overview about the main structure and sequence of things, so that other people than the current maintainers can get into the code faster.

**Comment by aeosynth** [comment]
can you show me some prior art. what's one specific thing you'd like detailed. you already know the sequence of things if you've hosted a draft.

**Comment by aeosynth** [comment]
and please open a new issue

**Comment by berserkingyadis** [comment]
since i dont have time for this atm ill close

**Comment by tooomm** [comment]
@berserkingyadis this repository is not maintained anymore.
Please go over to the follow up project with updated code base and more features @[dr4fter/dr4ft](https://github.com/dr4fters/dr4ft)!

If you have any concerns, ideas or request file them there - it's active and people will look into your issues.
