### ISSUE TITLE
SSL connection on draft.wtf not working properly

### ISSUE THREAD

**Issue by tooomm** [aeosynth/draft#143]
The https page doesn't display anything...

This are the information within Firefox:
![ssl1](https://cloud.githubusercontent.com/assets/9874850/13708322/40061a22-e7ae-11e5-9f34-9e15da9b331c.png)
![ssl2](https://cloud.githubusercontent.com/assets/9874850/13708327/427fbf74-e7ae-11e5-9257-6c190e8fe043.png)

**Comment by aeosynth** [comment]
yeah the site will probably never fully support https, because the images are loaded from gatherer which does not use https. the front page not loading is kind of moot.
