### ISSUE TITLE
Unable to build on OS X 10.10 and Ubuntu 14.04

### ISSUE THREAD

**Issue by ideocl4st** [aeosynth/draft#98]
>>npm install
mkdir -p public/lib
ln -sf /home/ideocl4st/draft/node_modules/normalize.css/normalize.css public/lib
ln -sf /home/ideocl4st/draft/node_modules/react/dist/react.js public/lib
ln -sf /home/ideocl4st/draft/node_modules/engine.io-client/engine.io.js public/lib
ln -sf /home/ideocl4st/draft/node_modules/traceur/bin/traceur.js public/lib
ln -sf /home/ideocl4st/draft/node_modules/traceur/bin/traceur-runtime.js public/lib
ln -sf /home/ideocl4st/draft/node_modules/ee/ee.js public/lib
ln -sf /home/ideocl4st/draft/node_modules/utils/utils.js public/lib
rm -f data/AllSets.json
curl -so data/AllSets.json http://mtgjson.com/json/AllSets.json
node src/make cards
node src/make score

>>/home/ideocl4st/draft/src/make/score.js:9
    throw err;
          ^
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
make: *** [score] Error 8

Both build environments give me the same error.

**Comment by aeosynth** [comment]
for now you can comment out the score line. i need to change hosts, it's always been pretty buggy
