### ISSUE TITLE
Non-basic Lands in Land slots for FRF packs

### ISSUE THREAD

**Issue by ideocl4st** [aeosynth/draft#99]
Just as it had been in DGM packs, FRF packs have a common tapland (two colors, gain 1 life) or rarely a fetchland in place of a basic land.

Is there a way to implement this in 'spoiler' scripts?

**Comment by aeosynth** [comment]
pull request welcome

**Comment by ideocl4st** [comment]
I did hack my way through it by cutting out DGM parts out of cards.js into spoiler scripts.

My implementation has a caveat though - non-english packs can have basic lands along with taplands and fetchlands in their land slot, so my hack reflects that by scraping basic lands in the spoiler page and slapping them in the 'special' rarity array.

Is it still okay to make a pull request?

**Comment by aeosynth** [comment]
i can comment on your pr

**Comment by aeosynth** [comment]
where did you get the information that english and non-english packs are different?

**Comment by ideocl4st** [comment]
http://magic.wizards.com/en/articles/archive/feature/fetching-look-fate-reforged-2014-12-24

"Certain languages—Korean, Portuguese, Chinese (Traditional), and Russian—will also contain basic lands in this slot at a high frequency alongside nonbasic lands, as Fate Reforged basic lands will not otherwise be printed in those languages. Other languages will typically not contain basic lands. The frequency at which fetch lands will appear is the same across all languages."

I guess I was partially wrong.

**Comment by aeosynth** [comment]
so all packs may contain a basic, tapland, or fetchland. don't worry about the other languages.

**Comment by aeosynth** [comment]
@ideocl4st will you make a pr?

**Comment by ideocl4st** [comment]
@aeosynth I have a final exam tomorrow so it'll a day or two before I can get on it.
You can go ahead if you'd like.

**Comment by aeosynth** [comment]
fixed
